<?php
// $helper = $this->helper('Bluethink\Verify\Helper\Data');
// $values = $helper->getConfigValue();

$values=$block->getBlogs();

if($values==1):

?>

<div id="popup-modal">
<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form"
              action="<?php echo $block->getFormAction(); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Fill Detail')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                    <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Name')) ?></span></label>
                            <div class="control">
                                <input name="name" id="name" title="name" value="" class="input-text"
                                       type="text" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('Email')) ?></span></label>
                            <div class="">
                                <input name="email" id="email" title="email" value="" class="input-text" type="text"
                                       data-validate="{required:true}">
                            </div>
                        </div>
              
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save"><span><?= $block->
                        escapeHtmlAttr(__('Save')) ?></span></button>
                </div>
            </div>
        </form>
     
    </div>
</div> 
</div>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Custom Form Popup',
                buttons: [{
                    text: $.mage.__('Close'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };
            var popup = modal(options, $('#popup-modal'));
            $('#popup-modal').modal('openModal');
        }
    );
</script>

<?php endif; ?> 

